apiVersion: v1
kind: Secret
metadata:
    name: headscale-config
    namespace: headscale
type: Opaque
stringData:
    config.yaml: ENC[AES256_GCM,data:ojQswhXnSbcG2EoGhfzqagQJ4sWTjxA5qR+zmtoj1ex1/nuKIzCSvPuumsoTY5bcOjMaKcjQdvifhoeC/y3EXK/2sVEYE61rkGuV6MRFIfCY0Lp5hDaAJOjy4thaTSfscb2+HGdSV9+Cpj0xYlZdZkSxE2yGx2SVITqRAvB9ban3/X2mWhCnorCe3jEKlsJAqzQxh+21+LiJ/0csZLBFBHtMjM56Rws7L73Lkl6W6CvGr7xPFEh1edsH5oiolfpjRSiy853ag1upOBFSDdXEv9YpulwThripMn7kbdY0B+IZ+spfPOeBpp3NSWAU+RnyZwek5vv9vbG4Z9w/9OEBb0U6cLwiFcMvqdxxkCsXUELlWDQQm5mbDxUJJxOQc0ihlmJemaLFISYnKikjbEZWXSe2IyM6N/LYri/hJp4ai89ea0z/8igYlV7DpjabdgHw3moLH95XhBuQYvsnnG0FN/T1BEEi/FTRdrj2vU3rD6oKnDP4YjD2s1On0PEAvvZokHkiO8aqql/XRxNnaWPciLvLwhsXbrewm0kfQyEheQ==,iv:+N9Dlv8hambjvTHbGjPXPqf/6+BUSBJglClcs3hbOFw=,tag:dXePPQsDgAHUGnZ87k8zag==,type:str]
sops:
    age:
        - recipient: age1hnjqvvs9nce37lxapmwctzgnfhwrvxcgejy8ut93n2w3mtt82q5qv6ng9v
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvc0xiKzNleUVmc3NtV2or
            QmNObmtlaU9HZkltSHNUckhkLzJpUkF6cDBrCjRMU2NacUVRbGpsd0hDT290VllK
            Ny9oUGh5VnNIZDdwWlN4UGhuRk1NbFUKLS0tIGgwTFMzaHF0aVI4VjJsOVV5cyta
            b3VXc1JrWHZmSG9haTY4eU41RFJDbzAK/Pu1PS6rkWtnrRMHZtSH0qg+MJGQ1IgN
            sGAyaZSAfLhQBWFtQs63N1v6X0G8H9UnM8jUaHE+HVbPJXxBtzkr+Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-28T11:29:50Z"
    mac: ENC[AES256_GCM,data:d8ifgS4xub7/QhufrZjBXyvw60A7Ea9Ht6LCqiH36dQC8jVmLf8oWRL68zaI1+eLNh7S9ptl/ceUDsbRnsgtSil59PiPD1JTUuIuTz3Ve8/X3/sKwg35qU3YCymYoFeJEsZOOUNCNYM+rjdrewhh0h1ZD2EvkOY1xx7dAZ1GuR4=,iv:MdCPVJum8iUQ4ydKjTpCXZAwuw5v6uZiXu9VbIWs4HU=,tag:VanIA0UN66ZrTehUQbOcFg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
