apiVersion: v1
kind: Secret
metadata:
    name: headscale-config
    namespace: headscale
type: Opaque
stringData:
    config.yaml: ENC[AES256_GCM,data:FpQMOalEY5pf84e6Iv5XZvo8wtnkay7TqDaGBdKm5ox5W+ASG+2tFPy6rRHEQsd7w5zKVQPYf3HNabtbw6+2uQ2pOT/ZeBwNFobdWAQvvHcWq1V52qHML0PKraY4+EaKQXQRWBh3c9kt5n0aEo4C5ZYVRACaYyIsVtlYqGv0bF3NVlLgQOPv/gGxfHEt1m6WvRRe8hbWDSuW8kRFjUbNnJw7ZNXIp+k58xyLYsGs9ZbOftPDoFVlGMCj6/I5tfILJF4hVX/P0YS5RUugcfpvqNpjcYW1V0GUu2qLNRGL2uSk9fsfq1H8D2229Dy6cA1mi8XchTXv4mnIODpddvmDbNZdfaMA5IJMBhHg+fq8K7LjUO3UJWwkY8KB7ZCQ1LvJqbYajha3WrWOIuAWAkv1J1pH7SwsOAZjmwc34798i0eeNbDMvp3DGN7oh7UVjIodkCqKczJ6buW/Q/8sBo1d1/+wC54tQf5JdvTRbVrGLx/QB+WVVMjKbT9Z9CvcEgAx4F7CDtyMMybOdjV77qROTYM5Td8ImH/gW8Lgq+Dqk4zvoctZrZ16NgDHevtzM+lbN5vUN/qtfSJr+CY9gA9QobZjgbpDmdp28aGcRpdUMuGRRZYnviFazIYXjl6E46JvPY26lvFOHwWy8keHjMeV7yOmObiC6ciVr/bBcjLDyqCmmvOE82zy2makt+aSOwnUaSJRm98fQ3wzx/cdzVX+ZtGIXMS0p7UYjwsvwrZjJit7DCNT906B/UfGHz9rAr/z9txTPOpL7QXzV20Rv3YAEqR+8p9JmF7Ty8Kjd/6cAcwOf5pje341a5qogS3CNDYHNKF6+h/srbcWAboac1Yec+dMT6hRj/XL8V5dRU7u2cxQjDoL6sF6IVTMHErGmN0JadLbD0yTqk+xmAc9uTdji5omI+48owWBFHdxiaZcAe0mJgXwjTF5lHG7uWYTEEehe8vZGQ==,iv:3bbqXVHqO0SFGpQvmvT60qUlt4PydzeCYOB8eGxRjeg=,tag:3kjX2mudw3An6DsVEbzhXA==,type:str]
sops:
    age:
        - recipient: age1hnjqvvs9nce37lxapmwctzgnfhwrvxcgejy8ut93n2w3mtt82q5qv6ng9v
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuSUx0bmltNWFXdjQzWFVq
            Yk0zZDZoODQxcUtrYkl0QnhmVkhpcEJ5akFJCktkV0RSSTB6eWluVmxRTDRrZmoy
            ZDYyZVlkS0xLYW5jbUh4ajBMbXJOVGsKLS0tICtVTWpBK01IWmdmeVBOdUx5WVd2
            U2g5eFlhR3laRTdSZnpoV0xoUVhuVEUKhmZkTQbMVtX2l46ArSc4fdH2BKEH1piW
            Rcf0l7fgWD9tqbxjJfFX74qJCOawKGT+MZu55DbXVwtbghqfdBdE1w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-28T13:37:20Z"
    mac: ENC[AES256_GCM,data:zgK/YxWi99zFO0xhZc2IJNqKSaCOAyq4OqTPzmQz1M6iVWZ3bGnJOkMopXJIwEh2HXV6gFKn6BsYB8Mssz+8HYv+GS3301QwQBRx3mCKzAzYsdMt8qv3KpY01Khc3QpAgp66XR3OCWSgq6TZb/zyxxlMZmhcim2NEJLxrcLLYFQ=,iv:K35J/skWhGRzfw6eCK/Yhs9WkCX8o1exafcSdgmGhMs=,tag:jG3VVeoue/4cG7fwMryWDA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
