apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: headscale
  namespace: headscale
spec:
  entryPoints:
    - websecure
  routes:
  - match: Host(`headscale.markonakic.xyz`) && PathPrefix(`/`) && !PathPrefix(`/.well-known/acme-challenge/`)
    kind: Rule
    priority: 1
    services:
    - name: headscale
      port: 8080
  tls:
    secretName: headscale-tls