apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: headscale
  namespace: headscale
spec:
  entryPoints:
    - websecure
  routes:
  - match: Host(`headscale.markonakic.xyz`)
    kind: Rule
    services:
    - name: headscale
      port: 8080
    middlewares:
    - name: headscale-security
  tls:
    certResolver: porkbun