apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: headscale
  namespace: headscale
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
    traefik.ingress.kubernetes.io/router.middlewares: traefik-traefik-security-headers@kubernetescrd
spec:
  ingressClassName: traefik
  tls:
  - hosts:
    - headscale.sarma.love
    secretName: sarma-wildcard-tls
  rules:
  - host: headscale.sarma.love
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: headscale
            port:
              number: 8080
