apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - helmrepository.yaml
  - postgresql-helmrepository.yaml
  - secret-postgresql.yaml
  - postgresql-helmrelease.yaml
  - helmrelease.yaml
  - service-derp.yaml
