apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: headscale
resources:
  - namespace.yaml
  - pvc.yaml
  - configmap-config.yaml
  - configmap-acl.yaml
  - deployment-headscale.yaml
  - service-headscale.yaml
  - service-derp.yaml
  - ingress.yaml
