apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - secret-db.yaml
  - secret-app.yaml
  - pvc-db.yaml
  - deployment-db.yaml
  - service-db.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
