apiVersion: v1
kind: Service
metadata:
  name: jellystat
  namespace: media
  labels:
    app: jellystat
    app.kubernetes.io/name: jellystat
spec:
  selector:
    app: jellystat
  ports:
    - name: http
      protocol: TCP
      port: 3000
      targetPort: http
  type: ClusterIP
