apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: media-stack
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./clusters/staging
  prune: true
  sourceRef:
    kind: GitRepository
    name: media-stack
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: qbittorrent
      namespace: media
    - apiVersion: apps/v1
      kind: Deployment
      name: sonarr
      namespace: media
    - apiVersion: apps/v1
      kind: Deployment
      name: radarr
      namespace: media
    - apiVersion: apps/v1
      kind: Deployment
      name: prowlarr
      namespace: media
    - apiVersion: apps/v1
      kind: Deployment
      name: bazarr
      namespace: media
    - apiVersion: apps/v1
      kind: Deployment
      name: jellyseerr
      namespace: media
