apiVersion: v1
kind: ConfigMap
metadata:
  name: headplane-config
  namespace: headscale
data:
  config.yaml: |
    server:
      host: "0.0.0.0"
      port: 3000
      cookie_secret_path: "/secrets/cookie-secret"
      cookie_secure: false
      cookie_max_age: 2592000
      disable_api_key_login: false

    headscale:
      url: "http://headscale:8080"
      api_key_path: "/secrets/api-key"
      config_strict: false
