apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: headplane
  namespace: headscale
spec:
  entryPoints:
    - web
  routes:
  - match: PathPrefix(`/admin`)
    kind: Rule
    priority: 10
    services:
    - name: headplane
      port: 3000