apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: headplane-internal
  namespace: headscale
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
    traefik.ingress.kubernetes.io/router.tls: "true"
spec:
  ingressClassName: traefik
  tls:
  - hosts:
    - headplane.sarma.xyz
    secretName: sarma-wildcard-cert
  rules:
  - host: headplane.sarma.xyz
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: headplane
            port:
              number: 3000
