apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: headplane
  namespace: headscale
spec:
  entryPoints:
    - websecure
  routes:
  - match: Host(`headplane.sarma.xyz`) && PathPrefix(`/`)
    kind: Rule
    priority: 1
    services:
    - name: headplane
      port: 3000
  tls:
    secretName: headplane-tls