apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: headscale
resources:
  - secret-headplane.yaml
  - deployment-headplane.yaml
  - service-headplane.yaml
  - ingress-headplane.yaml
