apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - serviceaccount.yaml
  - clusterrole.yaml
  - clusterrolebinding.yaml
  - secret-api-keys.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml

# Generate ConfigMap from glance.yml file
configMapGenerator:
  - name: glance-config
    namespace: glance
    files:
      - glance.yml
  - name: glance-css
    namespace: glance
    files:
      - glance-gruvbox.css
      - headscale-widget.css
