apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - serviceaccount.yaml
  - clusterrole.yaml
  - clusterrolebinding.yaml
  - secret-api-keys.yaml
  - configmap-glance.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml

# Generate ConfigMap for CSS files only
configMapGenerator:
  - name: glance-css
    namespace: glance
    files:
      - glance-gruvbox.css
      - widgets/headscale-nodes/style.css
