apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - helmrepository.yaml
  - secret-grafana-admin.yaml
  - helmrelease.yaml
  - ingress-grafana.yaml
  - ingress-prometheus.yaml
  - middleware-auth.yaml
