apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-credentials
    namespace: monitoring
type: Opaque
stringData:
    admin-user: ENC[AES256_GCM,data:kGSxQzo=,iv:c4Mhv5SrN0dVpV2JyjogY0a8NeHXI3Kg+gabGuSU/e8=,tag:WbAZlF9e67bjOqvmhRHJjg==,type:str]
    admin-password: ENC[AES256_GCM,data:hZsc5kAXU6O3A9nc7+7lFDIioHFP9bSR6n/IAwUblZRdfVgjVqDdCoSsPmk=,iv:xBXTW2qezqSOXFNjmTtqjsla+eqdK5qosKO94QyyiCM=,tag:5ukshkwXvzscdSbQUaaujQ==,type:str]
sops:
    age:
        - recipient: age1hujjuflxstf7fgzms6rgw6gpwh6kcs3yqv9qtu0js48gsa0h63js3xnvng
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrQ2Y0R0xCRWY0Y1ZtVSs4
            TGx0aTZDTkxsZnhpRDVheHJ0RzJSdXA5VGxJCjJrLzhQcmp4RGc4VkJNTktyMkV4
            d20vb2x0WCtzY0xXOXZoVWNkWjJsdTAKLS0tIGRGSll0TGpOWm9HMHcxWW9qODhI
            Y2FFUkJXL3U5ajAzM3NaaEJNYXV2YzgKrgx8B0EuvebB/LfSb7o4Iki48+vTkE8X
            vEdMLxggpiMGrgXw6abclEU9z7ILdYqYpKv/YvM8Q1Q46t7y1brEmA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-30T13:18:15Z"
    mac: ENC[AES256_GCM,data:7Sp9keS9Q42I4xWwZK1ZGCN4vRt83NzMH5V2u216jEt3HxUmZFWQ2jvd2PZt5+TQ0Q1YR289YS4TtCs6UlOPKiJW4s281A1cXYDNw0E9GZxVdBIXRiu/GOBZyud0OvzohQtXnMJuAzIB6IQrGCRY6X5yWnEustKdv8lvBwPra38=,iv:aRz1UYV0EB1GgLehkMniVaIqmvX6niApWBc11x+Cx8Q=,tag:B+e6yiVePyjRO8t93S5TfQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
