apiVersion: traefik.io/v1alpha1
kind: CertificateResolver
metadata:
  name: letsencrypt
  namespace: traefik
spec:
  acme:
    email: admin@sarma.xyz
    storage: /data/acme.json
    httpChallenge:
      entryPoint: web