apiVersion: v1
kind: Secret
metadata:
  name: porkbun-credentials
  namespace: traefik
type: Opaque
data:
  PORKBUN_API_KEY: cGsxX2YxMzQ4ODcyMTgxNDc4NGZhOWU3NTY2MjM0MzhhMGMzYjQ4OTgwMmZlNjljMGVmM2M0ZmJlYzk1ZTExOWZmZmMK
  PORKBUN_SECRET_API_KEY: c2sxX2IyNjAxZjgzNjY5MTkyNjAzZTg5ZWVkOWUzODdmYTI3ZWNjMzY3Y2Q0ODhmZTJjMTk0YmFkNmY0YjU0MWU4YTIK