apiVersion: v1
kind: ConfigMap
metadata:
  name: pihole-config
  namespace: pihole
data:
  # Pi-hole environment variables for best practices
  TZ: "Europe/Zagreb"
  WEBPASSWORD: ""  # Will be set via secret
  PIHOLE_DNS_: "1.1.1.1;9.9.9.9;8.8.8.8;8.8.4.4"
  DNSSEC: "true"
  DNS_BOGUS_PRIV: "true"
  DNS_FQDN_REQUIRED: "true"
  REV_SERVER: "true"
  REV_SERVER_DOMAIN: "sarma.xyz"
  REV_SERVER_TARGET: "192.168.0.200"
  REV_SERVER_CIDR: "192.168.0.0/24"
  # Local DNS records
  CUSTOM_DNS_1: "headscale.sarma.xyz=192.168.0.200"
  CUSTOM_DNS_2: "headplane.sarma.xyz=192.168.0.200"
  CUSTOM_DNS_3: "pihole.sarma.xyz=192.168.0.200"