apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base

  # example: if you ever want a staging-only tweak to Longhorn or Renovate,
  # you add strategic merge patches here
  # - path: longhorn-values-patch.yaml
