apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - helmrepository.yaml
  - helmrepository-porkbun.yaml
  - helmrelease.yaml
  - helmrelease-porkbun-webhook.yaml
  - secret-porkbun.yaml
  - clusterissuer.yaml
