apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - helmrepository.yaml
  - helmrelease.yaml
  - secret-porkbun.yaml
  - porkbun-webhook-helmrepository.yaml
  - porkbun-webhook-helmrelease.yaml
  - porkbun-webhook-rbac.yaml
  - clusterissuer.yaml
